const {acquireCronLock,listSubscriptions,saveSubscription,sendPush,getMarketState,setMarketState}=require('./push-server-lib');

function clean(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').replace(/USDT$/,'').slice(0,16)}
function pct(a,b){return a>0&&b>0?(b/a-1)*100:null}
function fmt(n){return Number.isFinite(n)?`${n>=0?'+':''}${n.toFixed(2)}%`:'—'}
function ema(v,n){if(!v.length)return 0;const k=2/(n+1);let e=v[0];for(const x of v.slice(1))e=x*k+e*(1-k);return e}
function pushLang(rec){const l=String(rec?.language||'pt-BR').toLowerCase();return l.startsWith('en')?'en':l.startsWith('es')?'es':'pt'}
function tx(rec,pt,en,es){const l=pushLang(rec);return l==='en'?en:l==='es'?es:pt}

async function fetchJson(url,ms=8500){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',signal:c.signal,headers:{Accept:'application/json','User-Agent':'Cripto-Radar-V16'}});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(t)}}
async function snapshot(){
 const sources=['https://data-api.binance.vision/api/v3/ticker/24hr','https://api.binance.com/api/v3/ticker/24hr'];
 for(const u of sources){try{const rows=await fetchJson(u);if(!Array.isArray(rows))continue;const assets=rows.filter(x=>x?.symbol?.endsWith('USDT')&&Number(x.quoteVolume)>0).map(x=>({symbol:x.symbol.slice(0,-4),change24h:Number(x.priceChangePercent)||0,volume:Number(x.quoteVolume)||0,last:Number(x.lastPrice)||0})).filter(x=>x.last>0);const sorted=[...assets].sort((a,b)=>a.volume-b.volume),n=sorted.length,rank=new Map(sorted.map((x,i)=>[x.symbol,n>1?Math.round(i/(n-1)*100):100]));assets.forEach(x=>x.liquidityPct=rank.get(x.symbol)||0);if(assets.length)return {assets,source:new URL(u).hostname}}catch(e){}}
 throw Error('Mercado indisponível');
}
async function klines(symbol,interval='15m',limit=80){const pair=clean(symbol)+'USDT';for(const base of ['https://data-api.binance.vision','https://api.binance.com']){try{const j=await fetchJson(`${base}/api/v3/klines?symbol=${encodeURIComponent(pair)}&interval=${encodeURIComponent(interval)}&limit=${limit}`);if(Array.isArray(j)&&j.length>=40)return j}catch(e){}}throw Error('Candles indisponíveis')}
function detectPullback(rows){
 if(!Array.isArray(rows)||rows.length<55)return null;const now=Date.now();let k=rows.filter(x=>{const ct=Number(x?.[6]);return !Number.isFinite(ct)||ct<=now+1500});if(k.length<50)return null;k=k.slice(-90);
 const close=k.map(x=>Number(x?.[4])),vol=k.map(x=>Number(x?.[5])||0),last=k.at(-1),lastClose=Number(last?.[4]),lastOpen=Number(last?.[1]);if(!(lastClose>0))return null;
 const e20=ema(close.slice(-70),20),e50=ema(close.slice(-90),50),lookback=8,prior=k.slice(Math.max(0,k.length-40),k.length-lookback);if(prior.length<20)return null;
 const resistance=Math.max(...prior.map(x=>Number(x?.[2])||0)),support=Math.min(...prior.map(x=>Number(x?.[3])||Infinity)),avgV=vol.slice(-28,-8).filter(x=>x>0),avg=avgV.length?avgV.reduce((a,b)=>a+b,0)/avgV.length:0;
 function build(side,level,bi){if(bi<0||bi>=k.length-2||!(level>0))return null;const after=k.slice(bi+1),bc=k[bi],bvol=Number(bc?.[5])||0;let rt=null;for(const c of after){const lo=Number(c?.[3]),hi=Number(c?.[2]),cl=Number(c?.[4]);if(side==='bull'){if(lo<=level*1.0045&&lo>=level*.994&&cl>=level*.997){rt=c;break}}else if(hi>=level*.9955&&hi<=level*1.006&&cl<=level*1.003){rt=c;break}}if(!rt)return null;const invalid=side==='bull'?after.some(c=>Number(c?.[4])<level*.992):after.some(c=>Number(c?.[4])>level*1.008);if(invalid)return null;const continuation=side==='bull'?lastClose>level*1.0015:lastClose<level*.9985;if(!continuation)return null;const ro=Number(rt?.[1]),rc=Number(rt?.[4]),rh=Number(rt?.[2]),rl=Number(rt?.[3]),body=Math.abs(rc-ro)||level*.0001,wick=side==='bull'?(Math.min(ro,rc)-rl):(rh-Math.max(ro,rc)),wickRatio=Math.max(0,wick/body),vr=avg>0?bvol/avg:1,dist=Math.abs((rc-level)/level)*100,trendOk=side==='bull'?e20>e50:e20<e50;let score=48;if(trendOk)score+=12;if(vr>=1)score+=7;if(vr>=1.5)score+=5;if(wickRatio>=.8)score+=7;if(wickRatio>=1.5)score+=4;if(dist<=.25)score+=7;if(side==='bull'&&lastClose>lastOpen)score+=5;if(side==='bear'&&lastClose<lastOpen)score+=5;score=Math.max(0,Math.min(96,Math.round(score)));if(score<68)return null;return{side,score,level,price:lastClose,candleTime:Number(last?.[0])||now,label:side==='bull'?'ALTA':'BAIXA'};}
 let bb=-1,sb=-1;for(let i=k.length-lookback;i<k.length-2;i++){const cl=Number(k[i]?.[4]);if(bb<0&&cl>resistance*1.0012)bb=i;if(sb<0&&cl<support*.9988)sb=i}const a=build('bull',resistance,bb),b=build('bear',support,sb);if(a&&b)return a.score>=b.score?a:b;return a||b||null;
}
function allowed(state,key,mins){const now=Date.now(),last=Number(state.cooldowns?.[key]||0);if(now-last<mins*60000)return false;state.cooldowns=state.cooldowns||{};state.cooldowns[key]=now;return true}
function prune(state){const now=Date.now();state.cooldowns=Object.fromEntries(Object.entries(state.cooldowns||{}).filter(([,v])=>now-Number(v)<36*3600000).sort((a,b)=>Number(b[1])-Number(a[1])).slice(0,1200));state.pullbacks=Object.fromEntries(Object.entries(state.pullbacks||{}).filter(([,v])=>now-Number(v?.seen||0)<8*3600000));}
function confirmPullback(state,symbol,p){state.pullbacks=state.pullbacks||{};const key=symbol+':'+p.side,old=state.pullbacks[key]||{count:0,sample:0,seen:0};if(Number(old.sample)!==Number(p.candleTime)){old.count=(Date.now()-Number(old.seen||0)<60*60000)?Math.min(2,Number(old.count||0)+1):1;old.sample=Number(p.candleTime);old.seen=Date.now();state.pullbacks[key]=old}return{...p,confirmations:Number(old.count||1),confirmed:Number(old.count||1)>=2}}
function userWatch(rec,assets){const held=(rec?.context?.wallet||[]).map(x=>clean(x.symbol)).filter(Boolean),defaults=['BTC','ETH','BNB','SOL','XRP','DOGE','ADA','LINK','SUI','AVAX'],top=[...assets].sort((a,b)=>b.volume-a.volume).slice(0,16).map(x=>clean(x.symbol));return new Set([...held,...defaults,...top])}
function mirrorBody(rec,x){const mirror=rec?.mirror||{},cap=Number(rec?.context?.portfolio?.totalBRL)||Number(mirror.userCapital)||100,riskPct=Math.max(.25,Math.min(2,Number(mirror.riskPct)||1)),stopPct=Math.max(.8,Math.min(4,Math.abs((x.price-x.level)/x.price)*100+.45)),allocPct=Math.max(2,Math.min(25,riskPct/stopPct*100)),alloc=cap*allocPct/100,l=pushLang(rec),loc=l==='en'?'en-US':l==='es'?'es-ES':'pt-BR',dir=x.side==='bull'?tx(rec,'ALTA','BULLISH','ALCISTA'):tx(rec,'BAIXA','BEARISH','BAJISTA');return l==='en'?`${dir} • ${x.score}/100 • simulation R$ ${alloc.toLocaleString(loc,{maximumFractionDigits:2})} • risk ${riskPct.toLocaleString(loc)}% • technical target ~2R`:l==='es'?`${dir} • ${x.score}/100 • simulación R$ ${alloc.toLocaleString(loc,{maximumFractionDigits:2})} • riesgo ${riskPct.toLocaleString(loc)}% • objetivo técnico ~2R`:`${dir} • ${x.score}/100 • simulação R$ ${alloc.toLocaleString(loc,{maximumFractionDigits:2})} • risco ${riskPct.toLocaleString(loc)}% • alvo técnico ~2R`}

module.exports=async(req,res)=>{
 res.setHeader('Cache-Control','no-store');if(req.method!=='GET')return res.status(405).json({ok:false,error:'Método não permitido'});
 try{
  if(!(await acquireCronLock(50)))return res.status(200).json({ok:true,skipped:true,reason:'scan já executado recentemente'});
  const subs=await listSubscriptions();if(!subs.length)return res.status(200).json({ok:true,subscriptions:0,sent:0});
  const snap=await snapshot(),assets=snap.assets,state=await getMarketState();state.cooldowns=state.cooldowns||{};state.pullbacks=state.pullbacks||{};const oldPrices=state.prevPrices||{},newPrices={};for(const x of assets)newPrices[clean(x.symbol)]=Number(x.last)||0;
  const kcache=new Map();let sent=0,failed=0;
  for(const rec of subs){
   if(rec.pendingLockedTest){const r=await sendPush(req,rec,{title:tx(rec,'🔒 Cripto Radar • tela bloqueada','🔒 Cripto Radar • locked screen','🔒 Cripto Radar • pantalla bloqueada'),body:tx(rec,'Teste automático recebido pelo servidor. Se você viu esta mensagem com o app fechado ou a tela bloqueada, o Push 24h está funcionando.','Automatic server test received. If you saw this with the app closed or the screen locked, 24h Push is working.','Prueba automática recibida del servidor. Si viste este mensaje con la app cerrada o la pantalla bloqueada, Push 24h funciona.'),tag:'radar-locked-test',url:'./',kind:'locked-test'});if(r.ok){sent++;await saveSubscription({...rec,pendingLockedTest:false,pendingLockedTestSentAt:new Date().toISOString()})}else failed++;}
   const watch=userWatch(rec,assets),cand=assets.filter(x=>watch.has(clean(x.symbol))&&Number(x.liquidityPct)>=70).sort((a,b)=>b.volume-a.volume);let userSent=0;
   for(const x of cand){if(userSent>=2)break;const s=clean(x.symbol),price=Number(x.last),move=pct(Number(oldPrices[s]),price),ch=Number(x.change24h)||0;
    if(Number.isFinite(move)&&Math.abs(move)>=0.55&&allowed(state,rec.id+':fast:'+s+(move>0?':up':':down'),10)){const r=await sendPush(req,rec,{title:(move>0?tx(rec,'🚀 Alta rápida: ','🚀 Fast rise: ','🚀 Subida rápida: '):tx(rec,'🔴 Queda rápida: ','🔴 Fast drop: ','🔴 Caída rápida: '))+s,body:tx(rec,`${fmt(move)} desde a última varredura • 24h ${fmt(ch)} • mercado ${snap.source}`,`${fmt(move)} since last scan • 24h ${fmt(ch)} • market ${snap.source}`,`${fmt(move)} desde el último escaneo • 24h ${fmt(ch)} • mercado ${snap.source}`),tag:'server-fast-'+s,url:'./#urgentRadarCard',kind:'market-fast',symbol:s});if(r.ok){sent++;userSent++}else failed++;continue}
    if(Math.abs(ch)>=7.5&&allowed(state,rec.id+':24h:'+s+(ch>0?':up':':down'),45)){const r=await sendPush(req,rec,{title:(ch>0?tx(rec,'🟢 Movimento forte: ','🟢 Strong move: ','🟢 Movimiento fuerte: '):tx(rec,'🔴 Atenção no mercado: ','🔴 Market alert: ','🔴 Atención en el mercado: '))+s,body:tx(rec,`${fmt(ch)} em 24h • liquidez ${Math.round(Number(x.liquidityPct)||0)}/100`,`${fmt(ch)} in 24h • liquidity ${Math.round(Number(x.liquidityPct)||0)}/100`,`${fmt(ch)} en 24h • liquidez ${Math.round(Number(x.liquidityPct)||0)}/100`),tag:'server-24h-'+s,url:'./#urgentRadarCard',kind:'market-24h',symbol:s});if(r.ok){sent++;userSent++}else failed++;}
   }
   const held=(rec?.context?.wallet||[]).map(x=>clean(x.symbol)).filter(Boolean),tops=[...assets].sort((a,b)=>b.volume-a.volume).slice(0,8).map(x=>clean(x.symbol)),syms=[...new Set([...held,'BTC','ETH','SOL','BNB','LINK','SUI',...tops])].filter(s=>watch.has(s)).slice(0,8);
   for(const s of syms){if(userSent>=3)break;try{let rows=kcache.get(s);if(!rows){rows=await klines(s);kcache.set(s,rows)}const raw=detectPullback(rows);if(!raw)continue;const p=confirmPullback(state,s,raw);if(!p.confirmed||p.score<72)continue;const k=rec.id+':pullback:'+s+':'+p.side;if(!allowed(state,k,45))continue;const mirrorOn=rec?.mirror?.mode==='alerts';const r=await sendPush(req,rec,{title:mirrorOn?tx(rec,'🪞 Espelhamento: ','🪞 Mirroring: ','🪞 Replicación: ')+s:(p.side==='bull'?tx(rec,'↗️ Falha de pullback: ','↗️ Pullback failure: ','↗️ Fallo de pullback: '):tx(rec,'↘️ Falha de pullback: ','↘️ Pullback failure: ','↘️ Fallo de pullback: '))+s,body:mirrorOn?mirrorBody(rec,p):tx(rec,`${p.label} • score técnico ${p.score}/100 • nível ${Number(p.level).toPrecision(7)} • preço ${Number(p.price).toPrecision(7)} • possível continuação ${p.side==='bull'?'da alta':'da baixa'}`,`${p.side==='bull'?'BULLISH':'BEARISH'} • technical score ${p.score}/100 • level ${Number(p.level).toPrecision(7)} • price ${Number(p.price).toPrecision(7)} • possible ${p.side==='bull'?'bullish':'bearish'} continuation`,`${p.side==='bull'?'ALCISTA':'BAJISTA'} • score técnico ${p.score}/100 • nivel ${Number(p.level).toPrecision(7)} • precio ${Number(p.price).toPrecision(7)} • posible continuación ${p.side==='bull'?'alcista':'bajista'}`),tag:'server-pullback-'+s+'-'+p.side,url:'./#urgentRadarCard',kind:'pullback',symbol:s});if(r.ok){sent++;userSent++}else failed++;}catch(e){}
   }
  }
  state.prevPrices=newPrices;state.at=Date.now();state.source=snap.source;prune(state);await setMarketState(state);
  return res.status(200).json({ok:true,subscriptions:subs.length,sent,failed,at:new Date().toISOString(),source:snap.source});
 }catch(e){return res.status(500).json({ok:false,error:String(e?.message||e),at:new Date().toISOString()});}
};
